#!/bin/sh

echo "Starting PlexVideoCleaner"

sleep 120

while [ 1 == 1 ];
do
    echo "Executing PlexVideoCleaner"
    cd /app
    ./PlexVideoCleaner.py
    sleep $PLEX_VIDEO_CLEANER_INTERVAL
done