#!/bin/sh

echo "Starting PlexVideoCleaner" >> /logs/plexcleaner.log.`date +'%Y%m%d'`

sleep 120

while [ 1 == 1 ];
do
    echo "Executing PlexVideoCleaner" >> /logs/plexcleaner.log.`date +'%Y%m%d'`
    cd /app
    ./PlexVideoCleaner.py >> /logs/plexcleaner.log.`date +'%Y%m%d'`
    sleep $PLEX_VIDEO_CLEANER_INTERVAL
done